/****************************************/
/* Author  : Mahmoud Hosny				*/
/* Date    : 24 Oct 2023				*/
/* Version : V01                        */
/****************************************/

#ifndef TIMER_CONFIG_H_
#define TIMER_CONFIG_H_
                                    /***** TIMER0 *****/
					
/** MODES OPTIONS :
1- Normal_MODE 	 		
2- PWM__PHASE_CORRECT_MODE										
3- CTC_MODE													
4- FAST_PWM_MODE
**/												
#define TIMER0_MODE 		FAST_PWM_MODE

/** PRESCALAR OPTIONS :
1- TIMER_0_NO_CLOCK	 			
2- TIMER_0_NO_PRESCALER			
3- TIMER_0_PRESCALER_8				
4- TIMER_0_PRESCALER_64			
5- TIMER_0_PRESCALER_265			
6- TIMER_0_PRESCALER_1024			
7- TIMER_0_EXT_CLK_SRC_FALING_EDGE
8- TIMER_0_EXT_CLK_SRC_RISING_EDGE								   
**/
#define TIMER0_PRESCALAR	TIMER_0_PRESCALER_64

/** OC0 OPTIONS :
1- OC0_DISCONNECTED	
2- NON_INVERTING_MODE	
3- INVERITNG_MODE
**/		
#define TIMER0_OC0_MODE		NON_INVERTING_MODE

									/***** TIMER1 ******/
									
/** MODES OPTIONS :
1- TIMER1_NORMAL_MODE 	 			
2- TIMER1_PWM_PHASECORRECT_8BIT	
3- TIMER1_PWM_PHASECORRECT_9BIT	
4- TIMER1_PWM_PHASECORRECT_10BIT	
5- TIMER1_CTC_MODE					
6- TIMER1_FAST_PWM_8BIT			
7- TIMER1_FAST_PWM_9BIT			
8- TIMER1_FAST_PWM_10BIT			
9- TIMER1_FAST_PWM	
**/																		
#define TIMER1_MODE 		TIMER1_FAST_PWM


/** PRESCALAR OPTIONS :
1- TIMER_1_NO_CLOCK	 			
2- TIMER_1_NO_PRESCALER			
3- TIMER_1_PRESCALER_8				
4- TIMER_1_PRESCALER_64			
5- TIMER_1_PRESCALER_265			
6- TIMER_1_PRESCALER_1024			
7- TIMER_1_EXT_CLK_SRC_FALING_EDGE
8- TIMER_1_EXT_CLK_SRC_RISING_EDGE
**/
#define TIMER1_PRESCALAR	TIMER_1_PRESCALER_64

/** OC1A MODE OPTIONS:
1- OCRA_DISCONNECTED	
2- OCRA_TOGGLE			
3- OCRA_NON_INVERTING	
4- OCRA_INVERTING		
**/

/** OC1B MODE OPTIONS:
1- OCRB_DISCONNECTED	
2- OCRB_TOGGLE			 
3- OCRB_NON_INVERTING 
4- OCRB_INVERTING		
**/


#endif