/****************************************/
/* Author  : Mahmoud Hosny				*/
/* Date    : 27 Oct 2023				*/
/* Version : V01                        */
/****************************************/

#ifndef TIMER_CONFIG_H
#define TIMER_CONFIG_H

/*******************************************/

/** OPTIONS:
1- NORMAL_MODE
2- PWM_PHASE_CORRECT_MODE
3- CTC_MODE
4- FAST_PWM_MODE
**/
#define TIMER_MODE FAST_PWM

/*******************************************/

/** CLOCK SELECTION OPTIONS :
1-STOP_TIMER
2-NO_PRESCALAR
3-PRESCALAR_DIV_FACTOR_8
4-PRESCALAR_DIV_FACTOR_64
5-PRESCALAR_DIV_FACTOR_256
6-PRESCALAR_DIV_FACTOR_1024
7-EXTERNAL_SOURCE_ON_FALLING_EDGE
8-EXTERNAL_SOURCE_ON_RISING_EDGE
**/
#define CLOCK_SELECTION  PRESCALAR_DIV_FACTOR_8

/*******************************************/

/** INTERRUPT OPTIONS :
1-COMPARE_MATCH_ISR_ENABLE
2-OVERFLOW_ISR_ENABLE
3-ISR_DISABLE 
**/

#define ISR_DISABLE
/*******************************************/

/** COMPARE OUTPUT MODE - FAST PWM 
1- NORMAL_OC0_DISCONNECTED_
2- CLEAR_OC0_ON_COMPARE 
3- SET_OC0_ON_COMPARE  
**/
#define OC0_FAST_PWM_MODE  CLEAR_OC0_ON_COMPARE

/********************************************/

/** COMPARE OUTPUT MODE - PHASE CORRECT PWM 
1- NORMAL_OPERATION_OC0_DISCONNECTED__ 
2- CLEAR_OC0_ON_UPCOUNTING_COMPARE_MATCH_SET_OC0_ON_DOWNCOUNTING 
3- SET_OC0_ON_UPCOUNTING_COMPARE_MATCH_CLEAR_OC0_ON_DOWNCOUNTING  
**/
#define OC0_PHASE_CORRECT_PWM_MODE  CLEAR_OC0_ON_UPCOUNTING_COMPARE_MATCH_SET_OC0_ON_DOWNCOUNTING

/********************************************/

/** COMPARE OUTPUT MODE - NON PWM 
1- NORMAL_OPERATION_OC0_DISCONNECTED
2- TOGGLE_OC0_ON_COMPARE_MATCH
3- CLEAR_OC0_ON_COMPARE_MATCH
4- SET_OC0_ON_COMPARE_MATCH
**/

#define OC0_CTC_NON_PWM_MODE NORMAL_OPERATION_OC0_DISCONNECTED

#endif